### PR TITLE
Lookup app servers using multiple SRV records

### PR DESCRIPTION
**Pull request by roback**
Preparation for when we have two datacenters to deploy to.

### CODE REVIEW

**Comment by roback** [comment]
The test failing has nothing to do with this PR :)

```
  1) Net::SSH supports the ed25519 algorithm
     Failure/Error: expect(Net::SSH::Authentication::ED25519Loader::LOADED).to be(true)
     
       expected true
            got false
     # ./spec/integration/net_ssh_spec.rb:5:in `block (2 levels) in <top (required)>'
```

**Comment by dentarg** [comment]
We should make the build green anyway :-) It was 10 months since we last ran the tests here, so I guess we haven't properly locked our dependencies, I think it would be good to do that

**Comment by dentarg** [comment]
I suspect this change

* net-ssh 4.2.0: https://travis-ci.org/twingly/capistrano-twingly/jobs/318288023 ✅ 
* net-ssh 5.0.2: https://travis-ci.org/twingly/capistrano-twingly/jobs/436112469 🔴

**Comment by roback** [comment]
> We should make the build green anyway :-)

Done! https://github.com/net-ssh/net-ssh/pull/563 was the cause behind the failure :)

**Comment by dentarg** [comment]
We also need to require net-ssh >= 5

```
$ bundle
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using bcrypt_pbkdf 1.0.0
Using bundler 1.16.1
Using ed25519 1.2.4
Using net-ssh 4.2.0
Bundle complete! 3 Gemfile dependencies, 4 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

~/Downloads/test
$ bundle exec ruby -e 'require "net/ssh"; p Net::SSH::Authentication::ED25519Loader::LOADED'
false
```

References:

* https://github.com/net-ssh/net-ssh/issues/565
* https://github.com/net-ssh/net-ssh/issues/478

**Comment by roback** [comment]
> We also need to require net-ssh >= 5

Ah, yes, of course :)

**Pull request merged**
